export const ISSUE_COLORS = {
  traffic:          { border: "#f59e0b", label: "Traffic",        cls: "civic-pill-traffic"  },
  traffic_safety:   { border: "#f59e0b", label: "Traffic Safety", cls: "civic-pill-traffic"  },
  street_lighting:  { border: "#6366f1", label: "Lighting",       cls: "civic-pill-lighting" },
  road_maintenance: { border: "#8b5cf6", label: "Roads",          cls: "civic-pill-roads"    },
  parks_facilities: { border: "#22c55e", label: "Parks",          cls: "civic-pill-parks"    },
  noise_complaint:  { border: "#f97316", label: "Noise",          cls: "civic-pill-noise"    },
  housing:          { border: "#ef4444", label: "Housing",        cls: "civic-pill-safety"   },
  utilities:        { border: "#06b6d4", label: "Utilities",      cls: "civic-pill-other"    },
  other:            { border: "#94a3b8", label: "Community",      cls: "civic-pill-other"    },
};

export const FORUM_THREADS = [
  {
    id: "demo-1",
    name: "Maria S.",
    role: "Parent & Resident",
    badge: "Top Contributor",
    issueType: "traffic_safety",
    text: "The crosswalk at Mill Ave and University Dr needs better lighting. My kids walk to school and it's terrifying in winter mornings.",
    location: "Mill Ave & University Dr",
    support: 34,
    status: "responded",
    urgency_score: 9,
    gov_response: "Thank you for your report regarding pedestrian lighting at Mill Ave and University Drive. Our Public Works team has reviewed the request and scheduled an on-site inspection for March 28th. We anticipate installation of two new LED pedestrian lights within 45 days pending budget approval. — Kevin Mattingly, Public Works Director",
  },
  {
    id: "demo-2",
    name: "James T.",
    role: "Business Owner",
    badge: "Active Voice",
    issueType: "street_lighting",
    text: "Three streetlights on Rural Road have been out for over a month. It's affecting foot traffic to my shop after dark.",
    location: "Rural Road near Library",
    support: 22,
    status: "Letter Sent to Public Works",
    urgency_score: 7,
  },
  {
    id: "demo-3",
    name: "Chen W.",
    role: "Graduate Student",
    badge: "New Member",
    issueType: "parks_facilities",
    text: "Kiwanis Park desperately needs shade structures. The playground equipment gets dangerously hot in summer — measured 160°F on the slide.",
    location: "Kiwanis Park",
    support: 48,
    status: "responded",
    urgency_score: 8,
    gov_response: "We appreciate the community's concern regarding Kiwanis Park shade structures. The Parks & Recreation Department has allocated $42,000 from the Capital Improvement Fund for new shade canopies. Installation is scheduled to begin April 15th. — Sarah Chen, Parks & Recreation Director",
  },
  {
    id: "demo-4",
    name: "Patricia M.",
    role: "Retired Teacher",
    badge: "Verified Resident",
    issueType: "road_maintenance",
    text: "The pothole on Apache Blvd near the 101 overpass has damaged at least 12 cars this month. We need emergency repair.",
    location: "Apache Blvd & 101",
    support: 56,
    status: "responded",
    urgency_score: 8,
    gov_response: "The pothole on Apache Blvd near the 101 overpass has been logged as Priority 1 in our repair queue. A crew has been dispatched and repair is expected within 72 hours. We apologize for the inconvenience. — Transportation Services, City of Tempe",
  },
  {
    id: "demo-5",
    name: "Carlos M.",
    role: "Residente",
    badge: "Verified Resident",
    issueType: "road_maintenance",
    text: "Hay un bache enorme en la calle Apache cerca del supermercado que lleva meses sin repararse. Ya dañó las llantas de mi carro y varios vecinos han tenido el mismo problema. Necesitamos una reparación urgente antes de que cause un accidente.",
    location: "Apache Blvd & McClintock Dr, Tempe",
    support: 18,
    status: "pending",
    urgency_score: 7,
    language: "es",
    created_at: "2026-03-22T10:00:00.000Z", // recent — shows near top
  },
];
