export const ISSUE_COLORS = {
  traffic:          { border: "#f59e0b", label: "Traffic",        cls: "civic-pill-traffic"  },
  traffic_safety:   { border: "#f59e0b", label: "Traffic Safety", cls: "civic-pill-traffic"  },
  street_lighting:  { border: "#6366f1", label: "Lighting",       cls: "civic-pill-lighting" },
  road_maintenance: { border: "#8b5cf6", label: "Roads",          cls: "civic-pill-roads"    },
  parks_facilities: { border: "#22c55e", label: "Parks",          cls: "civic-pill-parks"    },
  noise_complaint:  { border: "#f97316", label: "Noise",          cls: "civic-pill-noise"    },
  housing:          { border: "#ef4444", label: "Housing",        cls: "civic-pill-safety"   },
  utilities:        { border: "#06b6d4", label: "Utilities",      cls: "civic-pill-other"    },
  other:            { border: "#94a3b8", label: "Community",      cls: "civic-pill-other"    },
};

export const FORUM_THREADS = [
  {
    id: "demo-1",
    name: "Maria S.",
    role: "Parent & Resident",
    badge: "🏆 Top Contributor",
    issueType: "traffic_safety",
    text: "The crosswalk at Mill Ave and University Dr needs better lighting. My kids walk to school and it's terrifying in winter mornings.",
    location: "Mill Ave & University Dr",
    support: 34,
    status: "Under Review by City Council",
  },
  {
    id: "demo-2",
    name: "James T.",
    role: "Business Owner",
    badge: "📢 Active Voice",
    issueType: "street_lighting",
    text: "Three streetlights on Rural Road have been out for over a month. It's affecting foot traffic to my shop after dark.",
    location: "Rural Road near Library",
    support: 22,
    status: "Letter Sent to Public Works",
  },
  {
    id: "demo-3",
    name: "Chen W.",
    role: "Graduate Student",
    badge: "🌱 New Member",
    issueType: "parks_facilities",
    text: "Kiwanis Park desperately needs shade structures. The playground equipment gets dangerously hot in summer — measured 160°F on the slide.",
    location: "Kiwanis Park",
    support: 48,
    status: "Escalated to Council",
  },
  {
    id: "demo-4",
    name: "Patricia M.",
    role: "Retired Teacher",
    badge: "⭐ Verified Resident",
    issueType: "road_maintenance",
    text: "The pothole on Apache Blvd near the 101 overpass has damaged at least 12 cars this month. We need emergency repair.",
    location: "Apache Blvd & 101",
    support: 56,
    status: "Repair Scheduled",
  },
];
